# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8741f19c5a40ba2c30ccbbf647ef1b7405ae8c25325c22c5df5fe440fe0f28daef7aa81c0252b5284f246dd4481ee1e6e97f9480ff7b17928edf811204182032

test:
  secret_key_base: f2fcbe4581662a943b67ca8b8b92a61cb6ed722ee823872b91891df24d71e0661bf618a541732e22a4cc0571db10a3c4247976f368b1656e598c04531a12a511

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
